services:
  camoufox:
    build:
      context: camoufox
      dockerfile: Dockerfile
    hostname: camoufox
    volumes:
      - "./.env:/app/.env:ro"
      - "./bin:/app/bin"
      - "./data/userdata:/app/userdata"
    ports:
      - "9540:9540" # aichat-proxy api
      # - "9550:9550" # camoufox websocket
      - "9560:9560" # vnc
