services:
  camoufox:
    # build:
    #   context: camoufox
    #   dockerfile: Dockerfile
    image: registry.cn-shanghai.aliyuncs.com/starudream/aichat-proxy-camoufox:20250712
    platform: linux/amd64
    hostname: camoufox
    volumes:
      - "./.env:/app/.env:ro"
      - "./bin:/app/bin"
      - "./data/certs:/app/certs"
      - "./data/userdata:/app/userdata"
    ports:
      - "9540:9540" # aichat-proxy api
      - "9560:9560" # vnc
