// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "github repo",
            "url": "https://github.com/starudream/aichat-proxy"
        },
        "license": {
            "name": "Apache-2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/_sse.js": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "file"
                ],
                "summary": "TamperMonkey SSE Script File",
                "deprecated": true,
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "common"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/chat/completions": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Follows the exact same API spec as ` + "`" + `https://platform.openai.com/docs/api-reference/chat` + "`" + `",
                "produces": [
                    "application/json",
                    "text/event-stream"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Chat Completions",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "*",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/router.ChatCompletionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/router.ChatCompletionResp"
                        }
                    }
                }
            }
        },
        "/v1/models": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Follows the exact same API spec as ` + "`" + `https://platform.openai.com/docs/api-reference/models/list` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "model"
                ],
                "summary": "Model List",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/router.ListModelResp"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "tags": [
                    "common"
                ],
                "summary": "Show Version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config.Version"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "config.Version": {
            "type": "object",
            "properties": {
                "buildDate": {
                    "type": "string"
                },
                "compiler": {
                    "type": "string"
                },
                "gitCommit": {
                    "type": "string"
                },
                "gitTreeState": {
                    "type": "string"
                },
                "gitVersion": {
                    "type": "string"
                },
                "goVersion": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                }
            }
        },
        "router.ChatCompletionChoice": {
            "type": "object",
            "properties": {
                "delta": {
                    "description": "模型输出的增量内容（流式）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/router.ChatCompletionMessage"
                        }
                    ]
                },
                "finish_reason": {
                    "description": "模型停止输出原因",
                    "type": "string"
                },
                "index": {
                    "description": "消息索引",
                    "type": "integer"
                },
                "message": {
                    "description": "模型输出消息列表（非流式）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/router.ChatCompletionMessage"
                        }
                    ]
                }
            }
        },
        "router.ChatCompletionMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "内容",
                    "type": "string"
                },
                "reasoning_content": {
                    "description": "推理内容（仅响应）",
                    "type": "string"
                },
                "role": {
                    "description": "角色",
                    "type": "string"
                }
            }
        },
        "router.ChatCompletionReq": {
            "type": "object",
            "properties": {
                "messages": {
                    "description": "消息列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/router.ChatCompletionMessage"
                    }
                },
                "model": {
                    "description": "模型 Id",
                    "type": "string"
                },
                "stream": {
                    "description": "是否流式",
                    "type": "boolean"
                }
            }
        },
        "router.ChatCompletionResp": {
            "type": "object",
            "properties": {
                "choices": {
                    "description": "模型输出内容",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/router.ChatCompletionChoice"
                    }
                },
                "created": {
                    "description": "请求创建的时间戳（秒级）",
                    "type": "integer"
                },
                "id": {
                    "description": "请求的唯一标识",
                    "type": "string"
                },
                "model": {
                    "description": "模型 Id",
                    "type": "string"
                },
                "object": {
                    "description": "响应类型",
                    "type": "string"
                },
                "usage": {
                    "description": "用量",
                    "allOf": [
                        {
                            "$ref": "#/definitions/router.ChatCompletionUsage"
                        }
                    ]
                }
            }
        },
        "router.ChatCompletionUsage": {
            "type": "object",
            "properties": {
                "completion_tokens": {
                    "description": "输出 tokens",
                    "type": "integer"
                },
                "prompt_tokens": {
                    "description": "输入 tokens",
                    "type": "integer"
                },
                "total_tokens": {
                    "description": "总消耗 tokens",
                    "type": "integer"
                }
            }
        },
        "router.ListModelResp": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "模型列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/router.Model"
                    }
                },
                "object": {
                    "description": "固定为 list",
                    "type": "string"
                }
            }
        },
        "router.Model": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "integer"
                },
                "id": {
                    "description": "模型 Id",
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "owned_by": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "name": "common"
        },
        {
            "name": "file"
        },
        {
            "name": "model"
        },
        {
            "name": "chat"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"http"},
	Title:            "AIChat Proxy API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
