consumes:
- application/json
definitions:
  api.ChatCompletionChoice:
    properties:
      delta:
        allOf:
        - $ref: '#/definitions/api.ChatCompletionMessage'
        description: 模型输出的增量内容（流式）
      finish_reason:
        description: 模型停止输出原因
        type: string
      index:
        description: 消息索引
        type: integer
      message:
        allOf:
        - $ref: '#/definitions/api.ChatCompletionMessage'
        description: 模型输出消息列表（非流式）
    type: object
  api.ChatCompletionMessage:
    properties:
      content:
        allOf:
        - $ref: '#/definitions/api.ChatCompletionMessageContent'
        description: 内容
      reasoning_content:
        description: 推理内容（仅响应）
        type: string
      role:
        description: 角色
        type: string
    required:
    - role
    type: object
  api.ChatCompletionMessageContent:
    properties:
      listValue:
        description: 数组
        items:
          $ref: '#/definitions/api.ChatCompletionMessageContentPart'
        type: array
      stringValue:
        description: 文本
        type: string
    type: object
  api.ChatCompletionMessageContentPart:
    properties:
      image_url:
        allOf:
        - $ref: '#/definitions/api.ChatMessageImageURL'
        description: 图片
      text:
        description: 文本
        type: string
      type:
        description: 类型，可选 text、image_url
        type: string
    type: object
  api.ChatCompletionReq:
    properties:
      messages:
        description: 消息列表
        items:
          $ref: '#/definitions/api.ChatCompletionMessage'
        type: array
      model:
        description: 模型 Id
        type: string
      stream:
        description: 是否流式
        type: boolean
      thinking:
        allOf:
        - $ref: '#/definitions/api.ChatCompletionThinking'
        description: 推理配置
      tools:
        description: 工具
        items:
          $ref: '#/definitions/api.ChatCompletionTool'
        type: array
    required:
    - model
    type: object
  api.ChatCompletionResp:
    properties:
      choices:
        description: 模型输出内容
        items:
          $ref: '#/definitions/api.ChatCompletionChoice'
        type: array
      created:
        description: 请求创建的时间戳（秒级）
        type: integer
      id:
        description: 请求的唯一标识
        type: string
      model:
        description: 模型 Id
        type: string
      object:
        description: 响应类型
        type: string
      usage:
        allOf:
        - $ref: '#/definitions/api.ChatCompletionUsage'
        description: 用量
    type: object
  api.ChatCompletionThinking:
    properties:
      type:
        description: |-
          auto：自动思考模式
          enabled：开启思考模式
          disabled：关闭思考模式
        type: string
    type: object
  api.ChatCompletionTokens:
    properties:
      reasoning_tokens:
        description: 思维链 tokens
        type: integer
    type: object
  api.ChatCompletionTool:
    properties:
      function:
        allOf:
        - $ref: '#/definitions/api.ChatCompletionToolFunction'
        description: 工具定义
      type:
        description: 类型，可选 function
        type: string
    type: object
  api.ChatCompletionToolFunction:
    properties:
      description:
        description: 描述
        type: string
      name:
        description: 名称
        type: string
      parameters:
        description: 参数列表
    type: object
  api.ChatCompletionUsage:
    properties:
      completion_tokens:
        description: 输出 tokens
        type: integer
      completion_tokens_details:
        allOf:
        - $ref: '#/definitions/api.ChatCompletionTokens'
        description: 输出 tokens
      prompt_tokens:
        description: 输入 tokens
        type: integer
      total_tokens:
        description: 总消耗 tokens
        type: integer
    type: object
  api.ChatMessageImageURL:
    properties:
      detail:
        description: 图片的质量，可选 high、low、auto
        type: string
      url:
        description: 图片链接或图片的 Base64 编码
        type: string
    type: object
  api.Index:
    properties:
      app_name:
        type: string
      build_date:
        type: string
      git_version:
        type: string
    type: object
  api.ListModelResp:
    properties:
      data:
        description: 模型列表
        items:
          $ref: '#/definitions/api.Model'
        type: array
      object:
        description: 固定为 list
        type: string
    type: object
  api.Model:
    properties:
      created:
        type: integer
      id:
        description: 模型 Id
        type: string
      object:
        type: string
      owned_by:
        type: string
    type: object
info:
  contact:
    name: github repo
    url: https://github.com/starudream/aichat-proxy
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: AIChat Proxy API
  version: "1.0"
paths:
  /:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Index'
      summary: Index
      tags:
      - common
  /v1/chat/completions:
    post:
      description: Follows the exact same API spec as `https://platform.openai.com/docs/api-reference/chat`
      parameters:
      - description: Request
        in: body
        name: '*'
        required: true
        schema:
          $ref: '#/definitions/api.ChatCompletionReq'
      produces:
      - application/json
      - text/event-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ChatCompletionResp'
      security:
      - ApiKeyAuth: []
      summary: Chat Completions
      tags:
      - chat
  /v1/models:
    get:
      description: Follows the exact same API spec as `https://platform.openai.com/docs/api-reference/models/list`
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ListModelResp'
      security:
      - ApiKeyAuth: []
      summary: Model List
      tags:
      - model
produces:
- application/json
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- name: common
- name: model
- name: chat
